spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cinema
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    host: localhost
    port: 6379
  kafka:
    bootstrap-servers: localhost:9092
